title: 福尔摩斯探案之斑点带子案
msgtype: markdown
variables: [rounds, health, love, proof1, round1, proof2, round2]
stages:
  "1.1":
    chapter: 楔子
    story: |-
      > 1883年4月初的一天早晨，华生一觉醒来，便发现夏洛克·福尔摩斯穿的整整齐齐的站在床边。🌁窗外天色湛蓝，🐧几只麻雀上下翻飞。
      > “抱歉，吵醒你了，华生，”他说，“但你我今早注定这样，先是赫德森太太被敲门声吵醒，接着她报复似的来吵醒我，现在轮到我来吵醒你了。”
      > “出什么事了？🔥失火了吗？”
      > “来了一位委托人，是个年轻的女士。你不是对有(漂)趣(亮)的(的)案(女)子(人)很感兴趣吗，不要错过这个机会。”

      请@bot，输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto, calc, calc]
        param: ["1.2", "health+10", "love+10"]
  "1.2":
    chapter: 楔子
    story: |-
      > @sender，对华生来说，他最大的乐趣就是观察福尔摩斯进行调查工作，欣赏他迅速地作出推论。他作出推论之迅速，就好像是单凭直觉；但事实上，他的推论总是建立在逻辑基础之上。
      > 他匆忙地穿上衣服，然后和福尔摩斯一起来到了楼下的起居室。
      > 一位女士👩端坐窗前，身穿黑色衣服、蒙着厚厚的头纱。
      > “早上好，小姐姐。”福尔摩斯虽然母胎单身，但撩妹功夫了得，他叫人端了一杯热咖啡，往炉火里扔了几根柴火。

      请@bot，输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto]
        param: ["1.3"]
  "1.3": 
    chapter: 初见
    story: |-
      > 那位女士出于害怕和惊恐，脸色苍白、神情沮丧。她的双眼惊慌不安，仿佛正在被🐯狮子追逐的铃鹿。
      > 她的身材和样貌最多不过30岁，但头发却未老先衰、夹杂着几缕银丝。她的左手袖口溅了些许`泥点`，口袋里有一张露出半截的`车票`。

      @sender，福尔摩斯作出推理，说道: 
      - **A**: 你昨晚就到了贝克街，怎么隔了一晚才来找我？
      - **B**: 我知道，你是今天早上坐火车来的
      - **C**: 小姐，你的眼睛是我见过最美的星空
    choices:
      - keywords: [A, a, 昨晚, 昨天]
        description: |-
          > “可我是今天早上才来的啊，”这位女士一脸看待傻瓜的眼神，“福尔摩斯先生是不是有点走神了…”
          > `好感度`-3
          > 当前好感度: @love

          @sender，福尔摩斯连忙改口说道: 
          - **A**: ~~你昨晚就到了贝克街，怎么隔了一晚才来找我？~~
          - **B**: 我知道，你是今天早上坐火车来的
          - **C**: 小姐，你的眼睛是我见过最美的星空
        action: calc
        param: "love-3"
      - keywords: [B, b, 早上, 今天, 火车]
        description: ""
        action: [goto, calc]
        param: ["1.4", "love+1"]
      - keywords: [C, c, 星空, 小姐, 爱情, 美, 眼睛, 漂亮]
        description: |-
          > “死变态！”这位女士又害怕又生气，转身朝门口走去。
          > “小姐留步，刚刚那句话是华生说的！”
          > 虽然很窘迫，但小姐勉强留在了房间里，加上点怒气，脸色反而变得红润些了。
          > `好感度`-5
          > 当前好感度: @love

          @sender，为了救场，福尔摩斯接着说:
          - **A**: 你昨晚就到了贝克街，怎么隔了一晚才来找我？
          - **B**: 我知道，你是今天早上坐火车来的
          - **C**: ~~小姐，你的眼睛是我见过最美的星空~~
        action: calc
        param: "love-5"
  "1.4": 
    chapter: 初见
    story: |-
      > “这么说，你认识我？”这位女士大为吃惊，她的眼睛困惑而迷恋地注视着福尔摩斯。
      > `好感度`+1
      > 当前好感度: @love
      > “不认识，但我注意到你口袋里有一张💳回程车票的后半截。你一定是很早就动身的，还乘坐过🏇双轮单马车，在崎岖泥泞的路上行驶了一段路程。除了单马车外，其他车辆根本不会这样甩起泥巴。”

      @sender，此外，这位小姐一定坐在车夫的:
      - **左边👈**
      - **右边👉**
      - **车底🚗**
    choices:
      - keywords: [左, left]
        description: |-
          > “您真的好厉害。”这位女士显得更加佩服了。
          > 福尔摩斯解释道：“这没什么，因为只有坐在车夫左边，你才会在左手袖口沾到泥巴。”
          > “下面，请跟我们讲述一下你的遭遇吧。”他说。
          > `好感度`+2
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love+2"
      - keywords: [右, right]
        description: |-
          > “不好意思，我是坐在车夫左边的。”这位女士反驳说。
          > 福尔摩斯解释道：“那好吧，请你跟我们讲述一下你的遭遇”
          > `好感度`-1
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love-1"
      - keywords: [底, 上, 下, 东, 西, 南, 北, 前, 后]
        description: |-
          > “你说什么！？”这位女士很惊讶，“您疯了吧……”
          > 福尔摩斯连忙解释，“请别误会，女士，这只是个玩笑……不如请跟我们讲述一下你的遭遇吧。”
          > `好感度`-2.5
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love-2.5"
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "1.5"
  "1.5":
    chapter: 讲述
    story: |-
      > “我叫海伦·斯托纳，和继父住在一起，他是英国古老的罗伊洛特家族最后一个还活着的人。”她说。
      > 福尔摩斯点点头，“我很熟悉这个家族，曾经是英国最富有的家族之一，北至伯克郡，西至汉普郡。可是连续四代子嗣都荒淫浪荡、挥霍无度，几乎倾家荡产了。”
      > “继父在`印度`时娶了我的母亲，她是孟加拉炮兵司令斯托纳少将的年轻遗孀，斯托纳太太。我和`我的姐姐`朱莉亚是孪生姐妹，母亲再婚时，我们才两岁。母亲家里很富有，去世前立下`遗嘱`，那就是在我们结婚后，必须每年给我们每人至少300英镑。”

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "1.6"
  "1.6":
    chapter: 讲述
    story: |-
      > “继父喜欢和流浪的`吉卜赛人`混在一起，经常在庄园里接待他们。而且还非常喜欢`印度动物`，目前他有一只印度猎豹和一只狒狒，是一个记者送他的。村民们既害怕它们，也怕它们的主人。”
      > “我的姐姐死时才30岁，可她早已经两鬓斑白了。朱莉亚订婚后两天，继父知道了这一婚约，但没有表示反对。但婚礼前不到两周时，她便惨死家中。”

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto, calc, calc]
        param: ["1.7", "round1?round1:0", "proof1?proof1:0"]
  "1.7":
    chapter: 讲述
    story: |-
      > “福尔摩斯先生，请问您还想知道哪方面的细节？”这位女士问道。

      @sender，请为福尔摩斯做出选择（注意，时间有限，请在`5`个回合内集齐`3`条有效线索）:
      - **母亲遗产的数额**
      - **宅子的布局**
      - **有关吉卜赛人**
      - **姐姐死前做的事**
      - **警察的结论**
    choices:
      - keywords: [母亲, 遗产, 数额, 遗嘱, 英镑, 钱]
        description: |-
        action: [incr]
        param: [round1]
      - keywords: [宅, 房, 屋, 布局, 位置, 方位]
        description: |-
        action: [incr]
        param: [round1]
      - keywords: [吉卜赛, 外国人]
        description: |-
        action: [incr]
        param: [round1]
      - keywords: [姐姐, 死]
        description: |-
        action: [incr]
        param: [round1]
      - keywords: [警, 验尸官, 调查, 疑点, 结论]
        description: |-
        action: [incr]
        param: [round1]
  "10.1": 
    chapter: Game Over
    story: |-
      > 由于❤️好感度降到了 `@love`，这位女士决定不委托福尔摩斯先生来解决案子了。
      > 并且由于你的所作所为，福尔摩斯先生的声望在贝克街每况愈下，最终决定搬离贝克街13号……

      @sender，请输入“重置”来重新开始吧🌝
      - **重置**
    choices: {}
  "10.2": 
    chapter: Game Over
    story: |-
      > 斯托纳女士的继父突然破门而入，看到房间里的继女、夏洛克和华生，连开三枪。
      > 调查中止，当前回合数: @round1，当前线索数: @proof1

      @sender，请输入“重置”来重新开始吧🌝
      - **重置**
    choices: {}
dynamics:
  - conditions:
      chapter: "*"
      expression: love <= 0
    action: goto
    param: "10.1"
  - conditions:
      chapter: "*"
      expression: round1 > 5 && proof1 < 3
    action: goto
    param: "10.2"
defaults:
  - conditions:
      chapter: "*"
      keywords: [help, man, 帮助, 怎么玩, 你是谁]
    action: none
    description: |-
      > @sender，欢迎来到`@title`，这是一个`文字冒险游戏`，你通过输入`动作`或`指令`来推进剧情、获取帮助。
      > 一百多年来，《福尔摩斯探案集》📖被翻译成57种文字，畅销不衰，🎬衍生电影超过200部。
      > 《斑点带子案》作为二葱记忆深刻的一则短篇，有着离奇的剧情、阴森的氛围、意料之外的结局。
      > 现在，让我们以bot的形式，进入19世纪的英国，自己就是福尔摩斯，试试看你的决策，会把案子带到怎样的🧭方向。
      > 每个人都有`独立的进度和存档`，建议拉到小群中调戏和游玩呢😄
      
      游戏基本操作如下: 
      - **继续游戏**: 直接@我即可
      - **开始游戏**: start
      - **帮助**: help、man
      - **提示**: hint
      - **重置**: reset
  - conditions:
      chapter: "*"
      keywords: [hint, 提示]
    action: none
    description: "@sender，本小节没有提示😂"
  - conditions:
      chapter: "*"
      keywords: [reset, start, 重置, 回到开始, 重新开始, 开始游戏]
    action: reset
    description: "重置章节"
  - conditions:
      chapter: "*"
      keywords: []
    action: none
    description: "> 福尔摩斯愣了一下，感觉自己像个被傻几操控的提线布偶🌚🌝"