title: 福尔摩斯探案之斑点带子案
msgtype: markdown
variables: [rounds, health, love, proof1, round1, proof2, round2]
stages:
  "1.1":
    chapter: 楔子
    story: |-
      > 1883年4月初的一天早晨，华生一觉醒来，便发现夏洛克·福尔摩斯穿的整整齐齐的站在床边。🌁窗外天色湛蓝，🐧几只麻雀上下翻飞。
      > “抱歉，吵醒你了，华生，”他说，“但你我今早注定这样，先是赫德森太太被敲门声吵醒，接着她报复似的来吵醒我，现在轮到我来吵醒你了。”
      > “出什么事了？🔥失火了吗？”
      > “来了一位委托人，是个年轻的女士。你不是对有(漂)趣(亮)的(的)案(女)子(人)很感兴趣吗，不要错过这个机会。”

      请@bot，输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto, calc, calc]
        param: ["1.2", "health+10", "love+10"]
  "1.2":
    chapter: 楔子
    story: |-
      > @sender，对华生来说，他最大的乐趣就是观察福尔摩斯进行调查工作✍️，欣赏他迅速地作出推论。他作出推论之迅速，就好像是单凭直觉；但事实上，他的推论总是建立在逻辑基础之上。
      > 他匆忙地穿上衣服，然后和福尔摩斯一起来到了楼下的起居室。
      > 一位女士👩端坐窗前，身穿黑色衣服、蒙着厚厚的头纱。
      > “早上好，小姐姐。”福尔摩斯虽然母胎单身，但撩妹功夫了得，他叫人端了一杯热咖啡，往炉火里扔了几根柴火。

      请@bot，输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto]
        param: ["1.3"]
  "1.3": 
    chapter: 初见
    story: |-
      > 那位女士出于害怕和惊恐，脸色苍白、神情沮丧。她的双眼惊慌不安，仿佛正在被🐯狮子追逐的铃鹿。
      > 她的身材和样貌最多不过30岁，但头发却未老先衰、夹杂着几缕银丝。她的左手袖口溅了些许`泥点`，口袋里有一张露出半截的`车票`。

      @sender，福尔摩斯作出推理，说道: 
      - **A**: 你昨晚就到了贝克街，怎么隔了一晚才来找我？
      - **B**: 我知道，你是今天早上坐火车来的
      - **C**: 小姐，你的眼睛是我见过最美的星空
    choices:
      - keywords: [A, a, 昨晚, 昨天]
        description: |-
          > “可我是今天早上才来的啊，”这位女士一脸看待傻瓜的眼神，“福尔摩斯先生是不是有点走神了…”
          > `好感度`-3
          > 当前好感度: @love

          @sender，福尔摩斯连忙改口说道: 
          - **A**: ~~你昨晚就到了贝克街，怎么隔了一晚才来找我？~~
          - **B**: 我知道，你是今天早上坐火车来的
          - **C**: 小姐，你的眼睛是我见过最美的星空
        action: calc
        param: "love-3"
      - keywords: [B, b, 早上, 今天, 火车]
        description: ""
        action: [goto, calc]
        param: ["1.4", "love+1"]
      - keywords: [C, c, 星空, 小姐, 爱情, 美, 眼睛, 漂亮]
        description: |-
          > “死变态！”这位女士又害怕又生气，转身朝门口走去。
          > “小姐留步，刚刚那句话是华生说的！”
          > 虽然很窘迫，但小姐勉强留在了房间里，加上点怒气，脸色反而变得红润些了。
          > `好感度`-5
          > 当前好感度: @love

          @sender，为了救场，福尔摩斯接着说:
          - **A**: 你昨晚就到了贝克街，怎么隔了一晚才来找我？
          - **B**: 我知道，你是今天早上坐火车来的
          - **C**: ~~小姐，你的眼睛是我见过最美的星空~~
        action: calc
        param: "love-5"
  "1.4": 
    chapter: 初见
    story: |-
      > “这么说，你认识我？”这位女士大为吃惊，她的眼睛困惑而迷恋地注视着福尔摩斯。
      > `好感度`+1
      > 当前好感度: @love
      > “不认识，但我注意到你口袋里有一张💳回程车票的后半截。你一定是很早就动身的，还乘坐过🏇双轮单马车，在崎岖泥泞的路上行驶了一段路程。除了单马车外，其他车辆根本不会这样甩起泥巴。”

      @sender，此外，这位小姐一定坐在车夫的:
      - **左边👈**
      - **右边👉**
      - **车底🚗**
    choices:
      - keywords: [左, left]
        description: |-
          > “您真的好厉害。”这位女士显得更加佩服了。
          > 福尔摩斯解释道：“这没什么，因为只有坐在车夫左边，你才会在左手袖口沾到泥巴。”
          > “下面，请跟我们讲述一下你的遭遇吧。”他说。
          > `好感度`+2
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love+2"
      - keywords: [右, right]
        description: |-
          > “不好意思，我是坐在车夫左边的。”这位女士反驳说。
          > 福尔摩斯解释道：“那好吧，请你跟我们讲述一下你的遭遇”
          > `好感度`-1
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love-1"
      - keywords: [底, 上, 下, 东, 西, 南, 北, 前, 后]
        description: |-
          > “你说什么！？”这位女士很惊讶，“您疯了吧……”
          > 福尔摩斯连忙解释，“请别误会，女士，这只是个玩笑……不如请跟我们讲述一下你的遭遇吧。”
          > `好感度`-2.5
          > 当前好感度: @love

          @sender，请输入“继续”阅读下一节剧情: 
          - **继续**
        action: calc
        param: "love-2.5"
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "1.5"
  "1.5":
    chapter: 讲述
    story: |-
      > “我叫海伦·斯托纳，和继父住在一起，他是英国古老的罗伊洛特家族最后一个还活着的人。”她说。
      > 福尔摩斯点点头，“我很熟悉这个家族，曾经是英国最富有的家族之一，北至伯克郡，西至汉普郡。可是连续四代子嗣都荒淫浪荡、挥霍无度，几乎倾家荡产了。”
      > “继父在`印度`时娶了我的母亲，她是孟加拉炮兵司令斯托纳少将的年轻遗孀，斯托纳太太。我和`我的姐姐`朱莉亚是孪生姐妹，母亲再婚时，我们才两岁。母亲家里很富有，去世前立下`遗嘱`，那就是在我们结婚后，必须每年给我们每人至少300英镑。”

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "1.6"
  "1.6":
    chapter: 讲述
    story: |-
      > “继父喜欢和流浪的`吉卜赛人`混在一起，经常在庄园里接待他们。而且还非常喜欢`印度动物`，目前他有一只🐨印度猎豹和一只🐒狒狒，是一个记者送他的。村民们既害怕它们，也怕它们的主人。”
      > “我的姐姐死时才30岁，可她早已经两鬓斑白了。朱莉亚订婚后两天，继父知道了这一婚约，但没有表示反对。但婚礼前不到两周时，🕯️她便惨死家中。”

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: [goto, calc, calc]
        param: ["1.7", "round1?round1:0", "proof1?proof1:0"]
  "1.7":
    chapter: 讲述
    story: |-
      > “福尔摩斯先生，请问您还想知道哪方面的细节？”这位女士问道。

      @sender，请为福尔摩斯做出选择（注意，时间有限，请在`3`个回合内获知至少`2`条有效线索）:
      - **母亲遗产的数额**
      - **宅子的布局**
      - **姐姐死前做的事**
      - **警察的结论**
    choices:
      - keywords: [母亲, 遗产, 数额, 遗嘱, 英镑, 钱]
        description: |-
          > “我的母亲有一笔相当可观的财产，由于前夫作为🚀炮兵司令的缘故，每年进账不少于💰1000英镑。”斯托纳小姐慢慢说道。
          > 这则信息`不是`有效线索。
          > 当前回合数: @round1，当前线索数: @proof1

          @sender，请继续提问:
          - **母亲遗产的数额**
          - **宅子的布局**
          - **姐姐死前做的事**
          - **警察的结论**
        action: [incr]
        param: [round1]
      - keywords: [宅, 房, 屋, 布局, 位置, 方位]
        description: |-
          > “我们住的宅子极其古老，只有一侧的耳房还住着人。在这些卧室里，`第一间`时我继父的，`第二间`是我姐姐的，`第三间`时我自己的。这些房间之间彼此互不相通，但房门都朝向一条共同的过道。”斯托纳小姐说，“我讲清楚了吗？”
          > “十分清楚。”
          > 这则信息`是`有效线索。
          > 当前回合数: @round1，当前线索数: @proof1

          @sender，请继续提问:
          - **母亲遗产的数额**
          - **宅子的布局**
          - **姐姐死前做的事**
          - **警察的结论**
        action: [incr, incr]
        param: [round1, proof1]
      - keywords: [姐姐, 死]
        description: |-
          > “姐姐遇害那天晚上，她来我房间讲述了即将举行的婚礼。到了11点钟，她起身回自己房间，但走到门口时她突然担心地问我”，斯托纳小姐说，“她说，‘海伦，夜深人静的时候，你听到过有人吹口哨吗？’”
          > “‘从来没有。’”斯托纳回答她姐姐。
          > “‘怎么可能？这几天深夜3点左右，我总能听到轻轻的口哨声，搞不清那声音是哪里来的。’”
          > 这则信息`是`有效线索。
          > 当前回合数: @round1，当前线索数: @proof1

          @sender，请继续提问:
          - **母亲遗产的数额**
          - **宅子的布局**
          - **姐姐死前做的事**
          - **警察的结论**
          你有一个`新的`提问选项:
          - **有关口哨声**
        action: [incr, incr]
        param: [round1, proof1]
      - keywords: [警, 验尸官, 调查, 疑点, 结论]
        description: |-
          > “由于我继父在郡里臭名昭著，警察和验尸官都非常认真的调查了这个案子。但是他们找不到任何能让人信服的死因。”斯托纳小姐无奈的说道，“警察敲过墙壁，四周很坚固，发生意外时姐姐也确认独自在房间里，身上也没有暴力痕迹。”
          > 这则信息`不是`有效线索。
          > 当前回合数: @round1，当前线索数: @proof1

          @sender，请继续提问:
          - **母亲遗产的数额**
          - **宅子的布局**
          - **姐姐死前做的事**
          - **警察的结论**
        action: [incr]
        param: [round1]
      - keywords: [口哨, 声, 吹, 哨]
        description: |-
          > “那天晚上，我就一直有大难临头的感觉。那是一个暴风雨之夜，狂风怒吼，雨点噼啪噼啪地打在窗户上。突然，在嘈杂的风雨声中，传来一声女人惊恐的尖叫。那是姐姐的声音，就在我开启房门的时候，我仿佛听到了那样的`口哨声`。停了一会儿，我又听到金属的`哐啷`一声。”斯托纳小姐回忆说。
          > “姐姐这时正在剧痛地抽搐着，躺在地板上，发出凄厉的呐喊，‘啊，海伦，是那条`带斑点的带子`！’”斯托纳小姐脸色发白地说，“这时继父穿着睡衣匆忙出来，叫来了医生，但此时已经徒劳无功了……”
          > 这则信息`是`有效线索。
          > 当前回合数: @round1，当前线索数: @proof1

          @sender，请继续提问:
          - **母亲遗产的数额**
          - **宅子的布局**
          - **姐姐死前做的事**
          - **警察的结论**
        action: [incr, incr]
        param: [round1, proof1]
  "1.8":
    chapter: 讲述
    story: |-
      > 福尔摩斯总结道：“我们梳理一下关键线索。宅子的布局：继父、姐姐、你；你姐姐遇害前听到了`口哨声`和金属`哐啷`声；以及那条暴风雨夜你姐姐遇害时看到的那条带`斑点`的带子。你的思路很清楚，请继续讲述。”
      > 斯托纳小姐继续说：“最近我也要结婚了，两天前这所房子突然开始修缮。我的卧室被钻出破洞，不得不搬到姐姐丧命的房间里居住。就在昨晚，在我回想姐姐可怕的遭遇时，突然听到了相同的口哨声。我吓得魂不附体，天一亮就来找您了。”

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "1.9"
  "1.9":
    chapter: 讲述
    story: |-
      > 好长一阵子，谁都没有说话。福尔摩斯用手托着下巴，凝视着噼啪作响的炉火🔥
      > 最后，他打破了沉默，“现在虽然细节不多，但却已经刻不容缓。你先回家，我们随后就到。不知能否在你继父不知道的情况下，查看一下这些房间？”
      > 获得了肯定的答复后，斯托纳小姐放心地离开了，福尔摩斯目送她登上了马车。
      > 过了半晌，突然响起敲门声。

      @sender，请作出选择:
      - **开门**
      - **假装没听到**
    choices:
      - keywords: [开门, 打开, open]
        description: ""
        action: goto
        param: "2.1"
      - keywords: [没, 不, 假装, 闭, close]
        description: ""
        action: goto
        param: "2.2"
  "2.1":
    chapter: 闯入
    story: |-
      > 福尔摩斯打开🚪门，一个👮彪形大汉堵在门口。穿着古怪，像一个专家，又像个庄稼汉。他凶光毕露的深陷的眼睛和那细长的鹰钩鼻子，看起来活像一只苍老、残忍的猛禽🦅
      > “哪一位是福尔摩斯？”那位彪形大汉对着华生和福尔摩斯两人问道。

      @sender，福尔摩斯说: 
      - **是我**
      - **是他**
    choices:
      - keywords: [是, 不, i, am, me, you, he, him]
        description: ""
        action: goto
        param: "2.3"
  "2.2":
    chapter: 闯入
    story: |-
      > 突然，🚪门被撞开了，一个👮彪形大汉堵在门口。穿着古怪，像一个专家，又像个庄稼汉。他凶光毕露的深陷的眼睛和那细长的鹰钩鼻子，看起来活像一只苍老、残忍的猛禽🦅
      > “你俩谁他娘的是福尔摩斯？”那位彪形大汉对着华生和福尔摩斯两人吼道。

      @sender，福尔摩斯说: 
      - **是我**
      - **是他**
    choices:
      - keywords: [是, 不, i, am, me, you, he, him]
        description: ""
        action: goto
        param: "2.3"
  "2.3":
    chapter: 闯入
    story: |-
      > “我就是罗伊洛特医生，别来这套，我知道我继女刚来过你这，我在跟踪她，她对你们说什么了！”
      > 福尔摩斯微微一笑。
      > “我警告你，不要多管闲事。”

      @sender，福尔摩斯接下来:
      - **继续微笑**
      - **打他一拳**
    choices:
      - keywords: [继续, 微笑, open]
        description: ""
        action: goto
        param: "2.4"
      - keywords: [没, 不, 假装, 闭, close]
        description: ""
        action: goto
        param: "2.5"
  "2.4":
    chapter: 闯入
    story: |-
      > 福尔摩斯更加笑容可掬。
      > “你这个苏格兰场自命不凡的芝麻官！”看到福尔摩斯不为所动，这个彪形大汉突然害怕了。他甩出一句垃圾话，转身离开了。
      > “刚刚斯托纳女士提到她继父进城有事要办，我们趁这个机会赶紧去一趟。”福尔摩斯对华生说。

      @sender，请输入“继续”阅读下一节剧情: 
      - **继续**
    choices:
      - keywords: [继续, 下一步, jixu, continue, next]
        description: ""
        action: goto
        param: "3.1"
  "2.5":
    chapter: 闯入
    story: |-
      > 这个彪形大汉狠狠地挨了福尔摩斯一拳，重重地摔倒在地。
      > 福尔摩斯掏出手枪，对准了他的额头。

      @sender，请决定:
      - **开枪**: 为民除害，替天行道
      - **放走**: 饶人一命，查案要紧
    choices:
      - keywords: [开, 枪, 打死, shot]
        description: ""
        action: goto
        param: "10.3"
      - keywords: [放, 走, leave]
        description: ""
        action: goto
        param: "3.1"
  "3.1":
    chapter: 调查
    story: |-
      > 那里天气很好，阳光明媚，晴空中白云直飘。这春意盎然的景色和不详事件的调查，形成了鲜明的对照。
      > “对面就是罗伊洛特医生的房子了，斯托纳小姐就在前面，她继父还没回来，我们快过去吧。”福尔摩斯说道。

      施工中👷
      感谢您的游玩，请联系`@pixelcao`反馈游玩体验，欢迎拍砖🧱
    choices:
      - keywords: [继续, 下一步, continue, next]
        description: "> 目前只做完了前两章哟～"
        action: none
  "10.1": 
    chapter: Game Over
    story: |-
      > 由于❤️好感度降到了 `@love`，这位女士决定不委托福尔摩斯先生来解决案子了。
      > 并且由于你的所作所为，福尔摩斯先生的声望在贝克街每况愈下，最终决定搬离贝克街13号……

      @sender，请输入“重置”来重新开始吧🌝
      - **重置**
    choices: {}
  "10.2": 
    chapter: Game Over
    story: |-
      > 就在谈话间，斯托纳女士的继父突然破门而入，看到房间里的继女、夏洛克和华生，连开三枪🔫
      > 调查中止，当前回合数: @round1，当前线索数: @proof1

      @sender，请输入“重置”来重新开始吧🌝
      - **重置**
    choices: {}
  "10.3": 
    chapter: Game Over
    story: |-
      > 砰地一声，罗伊洛特的脑袋炸开了花。此时，贝克街上过往的路人慌张的找来警察👮‍♀️
      > 福尔摩斯和华生一起被抓了起来，虽然斯托纳小姐安然无恙，但福尔摩斯再也不能继续探案之路了……

      @sender，请输入“重置”来重新开始吧🌝
      - **重置**
    choices: {}
dynamics:
  - conditions:
      chapter: "*"
      expression: love <= 0
    action: goto
    param: "10.1"
  - conditions:
      chapter: "*"
      expression: round1 > 3 && proof1 < 2
    action: goto
    param: "10.2"
  - conditions:
      chapter: "*"
      expression: round1 > 3 && proof1 >= 2
    action: goto
    param: "1.8"
defaults:
  - conditions:
      chapter: "*"
      keywords: [help, man, 帮助, 怎么玩, 你是谁]
    action: none
    description: |-
      > @sender，欢迎来到`@title`，这是一个`文字冒险游戏`，你通过输入`动作`或`指令`来推进剧情、获取帮助。
      > 一百多年来，《福尔摩斯探案集》📖被翻译成57种文字，畅销不衰，🎬衍生电影超过200部。
      > 《斑点带子案》作为二葱记忆深刻的一则短篇，有着离奇的剧情、阴森的氛围、意料之外的结局。
      > 现在，让我们以bot的形式，进入19世纪的英国，自己就是福尔摩斯，试试看你的决策，会把案子带到怎样的🧭方向。
      > 每个人都有`独立的进度和存档`，建议拉到小群中调戏和游玩呢😄
      
      游戏基本操作如下: 
      - **继续游戏**: 直接@我即可
      - **开始游戏**: start
      - **帮助**: help、man
      - **提示**: hint
      - **重置**: reset
  - conditions:
      chapter: "*"
      keywords: [hint, 提示]
    action: none
    description: "@sender，本小节没有提示😂"
  - conditions:
      chapter: "*"
      keywords: [reset, start, 重置, 回到开始, 重新开始, 开始游戏]
    action: reset
    description: "重置章节"
  - conditions:
      chapter: "*"
      keywords: []
    action: none
    description: "> 福尔摩斯愣了一下，感觉自己像个被傻几操控的提线布偶🌚🌝"